### ISSUE TITLE
Why using Integer instead of int

### ISSUE THREAD

**Issue by lushl9301** [cly753/tinyMoblima#2]
any good feature? or may be using Integer instead of int is a good project style/practice?

I'm not sure. We need to unify these.....

**Comment by cly753** [comment]
I don't know...
all can be classss

**Comment by lushl9301** [comment]
a,hahahah

**Comment by imdreamrunner** [comment]
Basically Integer support null lah...
Sometimes useful.

Some people would say they are less efficient. It's true though, but Python and JavaScript and..... are always doing so lol

**Comment by lushl9301** [comment]
good!

**Comment by cly753** [comment]
wooowo..... sodesika
