### ISSUE TITLE
several things to go

### ISSUE THREAD

**Issue by lushl9301** [cly753/tinyMoblima#3]
# *1 register moviegoer
# *2 login (staff)
# *3 revenue
# *4 book system

**Comment by cly753** [comment]
- [x] register moviegoer
- [x] login (staff)
- [x] revenue
- [x] book system

**Comment by cly753** [comment]
- [x] present seats in cinema

**Comment by lushl9301** [comment]
- [x] some getXXX method

**Comment by cly753** [comment]
- [ ] list showtimes

**Comment by lushl9301** [comment]
no more big issue except different Time for a single movie right?

**Comment by cly753** [comment]
yup...

**Comment by cly753** [comment]
- [ ] data i/o

**Comment by lushl9301** [comment]
really want to press like button!

**Comment by cly753** [comment]
you are falling in love with facebook...

**Comment by blakegong** [comment]
We should implement data IO to which files? 
MovieLib and?

**Comment by blakegong** [comment]
And how to upload my source files ah?

**Comment by cly753** [comment]
MovieLib Cineplex MoviegoerLib?

**Comment by cly753** [comment]
and Time...

**Comment by blakegong** [comment]
Oh no so many! I tried Cineplex first. But did not really understand some details. So just tried MoviegoerLib first. Today no more commit already, must start to do 0002 now :(
